### ISSUE TITLE
About itodd

### ISSUE THREAD

**Issue by guan2000910** [YangHai-1218/RADet#11]
The itodd data set does not seem to give the true value of the test. What should I do?

**Comment by guan2000910** [comment]
As well as any detection results on the itodd test set please?

**Comment by plusgrey** [comment]
Hi, it seems like you can successfully train the network. Have you encountered the following error with YCBV? 

2024-06-30 11:12:46,305 - radet - INFO - workflow: [('train', 1)], max: 100000 iters
2024-06-30 11:12:46,305 - radet - INFO - Checkpoints will be saved to /home/user/Desktop/RADet/work_dirs/ycbv_r50_radet_pbr by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 186, in <module>
    main()
  File "tools/train.py", line 175, in main
    train_detector(
  File "/home/user/Desktop/RADet/radet/apis/train.py", line 168, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 118, in run
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 118, in <listcomp>
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 23, in __init__
    self.iter_loader = iter(self._dataloader)
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/user/anaconda3/envs/radet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/home/user/Desktop/RADet/radet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

The 'flag' attribute of the dataset is an empty list.
