### ISSUE TITLE
Error about 'mmdet'

### ISSUE THREAD

**Issue by tan-tao11** [YangHai-1218/RADet#4]
Good work for 6D object pose estimation!
However, an error occurred, when I was running 'python tools/test.py --config configs/bop/r50_ycbv_pbr.py --checkpoint checkpoints/radet_ycbv_pbr.pth --format-only --eval-options jsonfile_prefix=work_dirs/results/radet_ycbv_pbr'. It seems to relate to the 'mmdetection' package. Could you please tell me how to install the correct 'mmdetection' package or some other solutions? Thank you!
Detailed information:
Traceback (most recent call last):
  File "/data3/tantao/my_projects/RADet-main/test.py", line 13, in <module>
    from radet.apis import multi_gpu_test, single_gpu_test
  File "/data3/tantao/my_projects/RADet-main/radet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/data3/tantao/my_projects/RADet-main/radet/apis/inference.py", line 10, in <module>
    from radet.core import get_classes
  File "/data3/tantao/my_projects/RADet-main/radet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/data3/tantao/my_projects/RADet-main/radet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import fast_nms, multiclass_nms, multiclass_vote
  File "/data3/tantao/my_projects/RADet-main/radet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops import vote_nms
ModuleNotFoundError: No module named 'mmdet.ops'
Pip list:
Package             Version  Editable project location
------------------- -------- ---------------------------------------
addict              2.4.0
certifi             2023.5.7
contourpy           1.1.0
cycler              0.11.0
Cython              0.29.35
fonttools           4.41.1
importlib-metadata  6.8.0
importlib-resources 6.0.0
Jinja2              3.1.2
kiwisolver          1.4.4
markdown-it-py      3.0.0
MarkupSafe          2.1.3
matplotlib          3.4.3
mdurl               0.1.2
mkl-fft             1.3.1
mkl-random          1.2.2
mkl-service         2.4.0
mmcv                1.3.18
mmcv-full           1.3.18
mmdet               3.1.0    /data3/xx/download/mmdetection-main
mmengine            0.8.2
mmpycocotools       12.0.3
numpy               1.24.3
opencv-python       4.8.0.74
packaging           23.1
Pillow              10.0.0
pip                 23.1.2
platformdirs        3.9.1
pycocotools         2.0.6
Pygments            2.15.1
pyparsing           3.0.9
pyproject           1.3.1
python-dateutil     2.8.2
PyYAML              6.0.1
RADet               1.0.0    /data3/xx/my_projects/RADet-main
rich                13.4.2
scipy               1.11.1
setuptools          67.8.0
shapely             2.0.1
six                 1.16.0
termcolor           2.3.0
terminaltables      3.1.10
tomli               2.0.1
torch               1.10.0
torchaudio          0.10.0
torchvision         0.11.0
tornado             6.3.2
typing_extensions   4.7.1
wheel               0.38.4
yapf                0.40.1
zipp                3.16.2

**Comment by YangHai-1218** [comment]
Hi, sorry about the problem, and thanks for your interest in our work. There are some minor issues in the code, and I will fix them ASAP.

**Comment by YangHai-1218** [comment]
Sorry about the delay. The code has been fixed. Please check again.

**Comment by KerwenX** [comment]
Hi, @YangHai-1218 
I have met the same problem. I am not sure which version of the `mmdet` should I install.
Thank you for your time and consideration.
